name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push user-service
      working-directory: ./user-service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest

    - name: Build and push product-service
      working-directory: ./product-service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/product-service:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/product-service:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        kubectl apply -f k8s/user-service-deployment.yml
        kubectl apply -f k8s/product-service-deployment.yml
